### ISSUE TITLE
Error when running pipeline on data

### ISSUE THREAD

**Issue by shraimrawan** [zhenLiuXplr/MisER-project#1]
Hi, 

I am interested in aligning my long read data using your pipeline in hopes of getting better alignment of the reads. I ran your example and runs fine for me but when I run my data, it errors. Below is the error I see 

Traceback (most recent call last):
  File "/home/shraimr/miniconda3/envs/miser/bin/MisER", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/shraimr/miniconda3/envs/miser/lib/python3.11/site-packages/MisER/run_miser.py", line 103, in main
    run_multiprocess(
  File "/home/shraimr/miniconda3/envs/miser/lib/python3.11/site-packages/MisER/fix_small_exon_multiproc.py", line 663, in run_multiprocess
    annot_bed = parse_bed(annot_bed_path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shraimr/miniconda3/envs/miser/lib/python3.11/site-packages/MisER/fix_small_exon_multiproc.py", line 68, in parse_bed
    tx_dict["blockSizes"] = [np.int64(x) for x in tx_dict["blockSizes"].split(',') if len(x) > 0]
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'float' object has no attribute 'split'

I double checked all my files and I can't seem to find anything wrong in them. 

Hoping you can help!
Rawan

**Comment by zhenLiuXplr** [comment]
Hi, can you provide several lines in your BED files?

**Comment by zhenLiuXplr** [comment]
MisER only use standard BED12 file, which looks like this:
```
chrIS	6955486	6962816	R1_101_1	0	+	6955486	6962816	0	3	243,116,360	0,4897,6970
chrIS	6955560	6960050	R1_101_2	0	+	6955560	6960050	0	2	169,261	0,4229
chrIS	6790170	6829759	R1_102_1	0	+	6790170	6829759	0	7	126,332,103,172,124,192,441	0,4197,8685,9514,12143,31935,39148
chrIS	6790135	6808198	R1_102_2	0	+	6790135	6808198	0	6	161,332,103,172,43,551	0,4232,8720,9549,12259,17512
```
The last two columns means blockSizes and blockStarts, which should be the exon size and exon start position
